AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
 update wallets function

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Stage of build
  LibLayerArn:
    Type: String
    Default: ''
    Description: Arn of lib layer

Globals:
  Function:
    Timeout: 600

Resources:
  UpdateWalletsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../../../src/functions/appsync_resolvers/update_wallets/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
        - !Ref LibLayerArn
      Environment:
        Variables:
          STAGE: !Ref Stage
      Policies:
      #TODO reduce perms
        - Statement:
          - Sid: DynamoDBAccess
            Effect: Allow
            Action:
            - dynamodb:*
            Resource: !Sub arn:aws:dynamodb:us-east-1:${AWS::AccountId}:table/*
        - Statement:
          - Sid: SSMAccess
            Effect: Allow
            Action:
            - ssm:*
            Resource: '*'


### SSM PARAMS ###
  UpdateWalletsFunctionArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub update-wallets-function-arn-${Stage}
      Type: String
      Value: !GetAtt UpdateWalletsFunction.Arn
      Description: SSM Parameter for user ARN of update wallets function
      Tags:
        Environment: !Ref Stage
