
version: 0.2

# env:
#   variables:
#     STAGE: 'dev'

phases:
  build:
    commands:
      - cd infrastructure/storage/s3
      - aws cloudformation deploy --stack-name klubby-storage-$STAGE --template template.yaml --region us-east-1 --capabilities CAPABILITY_IAM --parameter-override Stage=$STAGE
      - cd ../dynamodb
      - aws cloudformation deploy --stack-name klubby-storage-dynamodb-$STAGE --template template.yaml --region us-east-1 --capabilities CAPABILITY_IAM --parameter-override Stage=$STAGE
