version: 0.2

phases:
  build:
    commands:
      - cd infrastructure/storage/s3
      - aws cloudformation deploy --stack-name klubby-storage-$STAGE --template template.yaml --region us-east-1 --capabilities CAPABILITY_IAM --parameter-override Stage=$STAGE
      - cd ../dynamodb
      - aws cloudformation deploy --stack-name klubby-storage-dynamodb-$STAGE --template template.yaml --region us-east-1 --capabilities CAPABILITY_IAM --parameter-override Stage=$STAGE
      - cd ../../authentication
      - aws cloudformation deploy --stack-name klubby-authentication-$STAGE --template template.yaml --region us-east-1 --capabilities CAPABILITY_IAM --parameter-overrides Stage=$STAGE NewUserFunction=add-new-user-funtion-$STAGE
      - cd ../appsync
      - ARTIFACTS_BUCKET=$(aws ssm get-parameter --name artifacts-bucket-name-dev --region us-east-1 --query Parameter.Value)
      - aws cloudformation deploy
        --s3-bucket $ARTIFACTS_BUCKET
        --stack-name klubby-appsync-$STAGE
        --template template.yaml
        --region us-east-1 
        --capabilities CAPABILITY_IAM
        --parameter-override
          Stage=$STAGE 
          UserTableName=user-table-name-$STAGE 
          ConversationTableName=conversation-table-name-$STAGE
          UserConversationBridgeTableName=userconversationbridge-table-name-$STAGE
          UserKlubBridgeTableName=userklubbridge-table-name-$STAGE
          KlubConversationBridgeTableName=klubconversationbridge-table-name-$STAGE
          MessageTableName=message-table-name-$STAGE
          KlubTableName=klub-table-name-$STAGE UserPoolId=userpool-id-$STAGE
      # - cd ../managed-blockchain
      # - aws cloudformation deploy --stack-name klubby-managed-blockchain-$STAGE --template template.yaml --region us-east-1 --capabilities CAPABILITY_IAM --parameter-override Stage=$STAGE
      # - cd ../sam-backends/add-new-user
      # - sam build
      # - sam deploy --stack-name add-new-user-function-$STAGE --s3-bucket klubby-prod-artifacts-bucket --capabilities CAPABILITY_IAM --region us-east-1 --no-fail-on-empty-changeset
      #TODO include deployment of FE-CICD in here