AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Default: klubby
    Description: Project name
    Type: String
  Stage:
    Default: dev
    Description: The deployment stage for this stack. Used to name a variety of different resources.
    Type: String

Resources:
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
        BucketName: !Sub ${ProjectName}-${Stage}-artifacts-bucket

  AndroidBuildBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
        BucketName: !Sub ${ProjectName}-android-build-${Stage}-bucket

  ReleaseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
        BucketName: !Sub ${ProjectName}-${Stage}-release-bucket

  DebugBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
        BucketName: !Sub ${ProjectName}-${Stage}-debug-bucket

  KlubAvatarBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
              - ETag
            MaxAge: 3600
        BucketName: !Sub ${ProjectName}-${Stage}-klub-avatar-bucket
    
    
    
  KlubAvatarBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KlubAvatarBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${KlubAvatarBucket}
              - !Sub arn:aws:s3:::${KlubAvatarBucket}/*
            Principal:
              AWS:
                - '*'

### SSM PARAMS ###
  ArtifactsBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub artifacts-bucket-name-${Stage}
      Type: String
      Value: !Ref ArtifactsBucket
      Description: SSM Parameter for artifacts bucket name
      Tags:
        Environment: !Ref Stage