AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  add-wallet

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Stage of build

Globals:
  Function:
    Timeout: 60

Resources:
  AddWalletFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add_wallet/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          STAGE: !Ref Stage
      Policies:
      #TODO reduce perms
        - Statement:
          - Sid: DynamoDBAccess
            Effect: Allow
            Action:
            - dynamodb:*
            Resource: !Sub arn:aws:dynamodb:us-east-1:${AWS::AccountId}:table/*
        - Statement:
          - Sid: SSMAccess
            Effect: Allow
            Action:
            - ssm:*
            Resource: '*'


### SSM PARAMS ###
  AddWalletFunctionArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub add-wallet-function-arn-${Stage}
      Type: String
      Value: !GetAtt AddWalletFunction.Arn
      Description: SSM Parameter for user ARN of add wallet function
      Tags:
        Environment: !Ref Stage
