version: 0.2

phases:
  build:
    commands:
      - ARTIFACTS_BUCKET=$(aws ssm get-parameter --name artifacts-bucket-name-$STAGE --region us-east-1 --query Parameter.Value --output text)
      - LAYER_SRC_BUCKET=$(aws ssm get-parameter --name layer-src-bucket-name-$STAGE --region us-east-1 --query Parameter.Value --output text)

    #----Zip and Upload Lib Src-------#
      - cd $CODEBUILD_SRC_DIR/infrastructure/sam-backends/layers
      - mkdir asset-output && cp -r $CODEBUILD_SRC_DIR/src/lib asset-output/python
      - zip -r lib.zip asset-output/python
      - aws s3 cp lib.zip s3://$LAYER_SRC_BUCKET/lib.zip

    # Deploy Layer Stack
      - cd $CODEBUILD_SRC_DIR/infrastructure/sam-backends/layers
      - sam deploy
        --template-file template.yaml
        --stack-name sam-backends-layers-$STAGE
        --capabilities CAPABILITY_IAM
        --region us-east-1
        --no-fail-on-empty-changeset
        --parameter-overrides
          ParameterKey=Stage,ParameterValue=$STAGE
          ParameterKey=ProjectName,ParameterValue=$PROJECT_NAME
          ParameterKey=SrcBucket,ParameterValue=$LAYER_SRC_BUCKET

    #get lib layer arn from ssm
      - LIB_LAYER_ARN=$(aws ssm get-parameter --name lib-layer-arn-$STAGE --region us-east-1 --query Parameter.Value --output text)

    #----Deploy add-new-user Function-------#
      - cd $CODEBUILD_SRC_DIR/infrastructure/sam-backends/add-new-user
      - sam build
      - sam deploy
        --stack-name add-new-user-function-$STAGE
        --s3-bucket $ARTIFACTS_BUCKET
        --capabilities CAPABILITY_IAM
        --region us-east-1
        --no-fail-on-empty-changeset
        --parameter-overrides
            ParameterKey=Stage,ParameterValue=$STAGE

    #----Deploy landing-page Function-------#
      #not actually deploying this for now


    #----Deploy web3-queries Function-------#
      - cd ../web3-queries
      - sam build
      - sam deploy
        --stack-name klubby-$STAGE-web3-queries
        --s3-bucket $ARTIFACTS_BUCKET
        --capabilities CAPABILITY_IAM
        --region us-east-1
        --no-fail-on-empty-changeset
        --parameter-overrides
          ParameterKey=Stage,ParameterValue=$STAGE

  #----Deploy attached-file-presigned-url Function-------#
      - cd ../appsync_resolvers/create-attached-file-presigned-url
      - sam build
      - sam deploy
        --stack-name klubby-$STAGE-create-attached-file-presigned-url
        --s3-bucket $ARTIFACTS_BUCKET
        --capabilities CAPABILITY_IAM
        --region us-east-1
        --no-fail-on-empty-changeset
        --parameter-overrides
          ParameterKey=Stage,ParameterValue=$STAGE

  #----Deploy create-presigned-url Function-------#
      - cd ../create-klub-avatar-presigned-url
      - sam build
      - sam deploy
        --stack-name klubby-$STAGE-create-presigned-url
        --s3-bucket $ARTIFACTS_BUCKET
        --capabilities CAPABILITY_IAM
        --region us-east-1
        --no-fail-on-empty-changeset
        --parameter-overrides
          ParameterKey=Stage,ParameterValue=$STAGE


  #----Deploy delete-klub Function-------#
      - cd ../delete-klub
      - sam build
      - sam deploy
        --stack-name klubby-$STAGE-delete-klub
        --s3-bucket $ARTIFACTS_BUCKET
        --capabilities CAPABILITY_IAM
        --region us-east-1
        --no-fail-on-empty-changeset
        --parameter-overrides
          ParameterKey=Stage,ParameterValue=$STAGE

  #----Deploy join-klub Function-------#
      - cd ../join-klub
      - sam build
      - sam deploy
        --stack-name klubby-$STAGE-join-klub
        --s3-bucket $ARTIFACTS_BUCKET
        --capabilities CAPABILITY_IAM
        --region us-east-1
        --no-fail-on-empty-changeset
        --parameter-overrides
          ParameterKey=Stage,ParameterValue=$STAGE

  #----Deploy validate-address Function-------#
      - cd ../validate-address
      - sam build
      - sam deploy
        --stack-name klubby-$STAGE-validate-address
        --s3-bucket $ARTIFACTS_BUCKET
        --capabilities CAPABILITY_IAM
        --region us-east-1
        --no-fail-on-empty-changeset
        --parameter-overrides
          ParameterKey=Stage,ParameterValue=$STAGE

  #----Deploy update-wallets Function-------#
      - cd ../update-wallets
      - sam build
      - sam deploy
        --stack-name klubby-$STAGE-update-wallets
        --s3-bucket $ARTIFACTS_BUCKET
        --capabilities CAPABILITY_IAM
        --region us-east-1
        --no-fail-on-empty-changeset
        --parameter-overrides
          ParameterKey=Stage,ParameterValue=$STAGE
          ParameterKey=LibLayerArn,ParameterValue=$LIB_LAYER_ARN
