version: 0.2

phases:
  build:
    commands:
      - cd infrastructure/sam-backends/add-new-user
      - sam build
      - sam deploy \
        --stack-name add-new-user-function-prod \
        --s3-bucket klubby-prod-artifacts-bucket \
        --capabilities CAPABILITY_IAM \
        --region us-east-1 \
        --no-fail-on-empty-changeset \
        --parameter-overrides \
            ParameterKey=Stage,ParameterValue=prod
      - ls