
AWSTemplateFormatVersion: '2010-09-09'
Description: AppSync Stack
Parameters:
  ProjectName:
    Type: String
    Default: klubby
    Description: Unique Auth Name for Cognito Resources
  Stage:
    Type: String
    Default: dev
    Description: Stage of build
  UserPoolId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: userpool-id-dev
    Description: user pool id from SSM
  UserTableName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: user-table-name-dev
    Description: user table name
  ConversationTableName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: conversation-table-name-dev
    Description: conversation table name
  UserConversationsTableName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: userconversations-table-name-dev
    Description: user conversation table name
  MessageTableName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: message-table-name-dev
    Description: message table name
Resources:
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub '${ProjectName}-graphql-${Stage}'
      AuthenticationType: "AMAZON_COGNITO_USER_POOLS"
      UserPoolConfig:
        UserPoolId: !Ref UserPoolId
        AwsRegion: us-east-1
        DefaultAction: ALLOW
        # Ref: defaultAction
  Schema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      # DefinitionS3Location:
      #   Ref: graphQlSchemaS3DescriptionLocation
      Definition: |
        schema {
            query: Query
            mutation: Mutation
            subscription: Subscription
        }

        type Conversation {
          #  The Conversation's timestamp.
          createdAt: String
          #  A unique identifier for the Conversation.
          id: ID!
          #  The Conversation's messages.
          messages(after: String, first: Int): MessageConnection
          #  The Conversation's name.
          name: String!
        }

        type Message {
          #  The author object. Note: `authorId` is only available because we list it in `extraAttributes` in `Conversation.messages`
          author: User
          #  The message content.
          content: String!
          #  The id of the Conversation this message belongs to. This is the table primary key.
          conversationId: ID!
          #  The message timestamp. This is also the table sort key.
          createdAt: String
          #  Generated id for a message -- read-only
          id: ID!
          #  Flag denoting if this message has been accepted by the server or not.
          isSent: Boolean
          recipient: User
          sender: String
        }

        type MessageConnection {
          messages: [Message]
          nextToken: String
        }

        type User {
          username: String!
          wallets: String
          #  A user's enrolled Conversations. This is an interesting case. This is an interesting pagination case.
          conversations(after: String, first: Int): UserConverstationsConnection
          messages(after: String, first: Int): MessageConnection
        }

        type UserConversations {
          associated: [UserConversations]
          conversation: Conversation
          conversationId: ID!
          user: User
          userId: ID!
        }

        type UserConverstationsConnection {
          nextToken: String
          userConversations: [UserConversations]
        }

        type Query {
          getUsers: [User]
          getUserWallets(username: String!): User
          me:User
          getAllMessage(after: String, conversationId: ID!, first: Int): [Message]
          getAllMessageConnection(after: String, conversationId: ID!, first: Int): MessageConnection
          getAllMessageFrom(after: String, conversationId: ID!, first: Int, sender: String!): [Message]          
        }

        type Mutation {
          #  Create a Conversation. Use some of the cooked in template functions for UUID and DateTime.
          createConversation(createdAt: String, id: ID!, name: String!): Conversation

          #  Create a message in a Conversation.
          createMessage(content: String, conversationId: ID!, createdAt: String!, id: ID!): Message

          # Create a user conversation.
          createUserConversations(conversationId: ID!, userId: ID!): UserConversations
          # addUser(username: String!): User
          updateUser(username: String!,wallets: String!): User
        }

  UserDynamoDBTableDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: "UserDynamoDBTable"
      Description: The Post DynamoDB table
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        AwsRegion: "us-east-1"
        TableName: !Ref UserTableName
  ConversationDynamoDBTableDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: "ConversationDynamoDBTable"
      Description: The Conversation DynamoDB table
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        AwsRegion: "us-east-1"
        TableName: !Ref ConversationTableName
  UserConversationsDynamoDBTableDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: "UserConversationsDynamoDBTable"
      Description: The User Conversation DynamoDB table
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        AwsRegion: "us-east-1"
        TableName: !Ref UserConversationsTableName

  MessageDynamoDBTableDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: "MessageDynamoDBTable"
      Description: Message DynamoDB table
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        AwsRegion: "us-east-1"
        TableName: !Ref MessageTableName



  AppSyncDynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource: '*'

  ### Resolvers ###
  CreateConversationMutationResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: "Mutation"
      FieldName: "createConversation"
      DataSourceName: !GetAtt ConversationDynamoDBTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "operation" : "PutItem",
          "key": {
              "id": { "S" : "${context.arguments.id}"}
          },
          "attributeValues" : {
             "id": {  "S": "${context.arguments.id}" },
             "name": {  "S": "${context.arguments.name}" }
             #if(${context.arguments.createdAt}) ,"createdAt": { "S": "${context.arguments.createdAt}"} #end
          }
        }
      ResponseMappingTemplate: |
        $utils.toJson($context.result)

  CreateUserConversationsMutationResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: "Mutation"
      FieldName: "createUserConversations"
      DataSourceName: !GetAtt UserConversationsDynamoDBTableDataSource.Name
      RequestMappingTemplate: |
        {
            "version" : "2017-02-28",
            "operation" : "PutItem",
            "key": {
                "userId": { "S" : "${context.arguments.userId}"},
                "conversationId": { "S" : "${context.arguments.conversationId}"}
            },
            "attributeValues" : {
                "userId": {  "S": "${context.arguments.userId}" },
                "conversationId": {  "S": "${context.arguments.conversationId}" }
            }
        }
      ResponseMappingTemplate: |
        $utils.toJson($context.result)



  CreateMessageMutationResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: "Mutation"
      FieldName: "createMessage"
      DataSourceName: !GetAtt MessageDynamoDBTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "operation" : "PutItem",
          "key" : {
              "conversationId" : { "S" : "${context.arguments.conversationId}" }
          },
          "attributeValues" : {
              "conversationId": {  "S": "${context.arguments.conversationId}" },
              "content": {  "S": "${context.arguments.content}" },
              "createdAt": {  "S": "${context.arguments.createdAt}" },
              "sender": {  "S": "${context.identity.username}" },
              "isSent": {  "BOOL": true },
              "id": { "S": "${context.arguments.id}" }
          }
        }

      ResponseMappingTemplate: |
        $utils.toJson($context.result)


  GetUsersQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Query
      FieldName: getUsers
      DataSourceName: !GetAtt UserDynamoDBTableDataSource.Name
      RequestMappingTemplate: |
        {
            "version" : "2017-02-28",
            "operation" : "Scan",
            ## Add 'limit' and 'nextToken' arguments to this field in your schema to implement pagination. **
            ## "limit": $util.defaultIfNull(${ctx.args.limit}, 20),
            ## "nextToken": $util.toJson($util.defaultIfNullOrBlank($ctx.args.nextToken, null))
        }
      ResponseMappingTemplate: |
        #**
            Return a flat list of results from a Query or Scan operation.
        *#
        $util.toJson($ctx.result.items)

  GetUserWalletsQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Query
      FieldName: getUserWallets
      DataSourceName: !GetAtt UserDynamoDBTableDataSource.Name
      RequestMappingTemplate: |
        {
            "version": "2017-02-28",
            "operation": "GetItem",
            "key": {
                "username": $util.dynamodb.toDynamoDBJson($ctx.args.username),
            }
        }
      ResponseMappingTemplate: |
        ## Pass back the result from DynamoDB. **
        $util.toJson($ctx.result)

  meQueryResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: "Query"
      FieldName: "me"
      DataSourceName: !GetAtt UserDynamoDBTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "operation" : "GetItem",
          "key": {
              "username": { "S" : "${context.identity.username}"}
          }
        }
      ResponseMappingTemplate: |
        $utils.toJson($context.result)


  getAllMessageConnectionQueryResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: "Query"
      FieldName: "getAllMessageConnection"
      DataSourceName: !GetAtt MessageDynamoDBTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "operation" : "Query",
          "query" : {
              "expression": "conversationId = :conversationId",
              "expressionValues" : {
                  ":conversationId" : {
                      "S" : "${context.arguments.conversationId}"
                  }
              }
          },
          "scanIndexForward": false,
          "limit": #if(${context.arguments.first}) ${context.arguments.first} #else 20 #end,
          "nextToken": #if(${context.arguments.after}) "${context.arguments.after}" #else null #end
        }
        ResponseMappingTemplate: |
        {
          "messages": $utils.toJson($context.result.items),
          "nextToken": #if(${context.result.nextToken}) "${context.result.nextToken}" #else null #end
        }


  getAllMessageQueryResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: "Query"
      FieldName: "getAllMessage"
      DataSourceName: !GetAtt MessageDynamoDBTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "operation" : "Query",
          "query" : {
              "expression": "conversationId = :id",
              "expressionValues" : {
                  ":id" : {
                      "S" : "${context.arguments.conversationId}"
                  }
              }
          },
          "limit": #if(${context.arguments.first}) ${context.arguments.first} #else 20 #end,
          "nextToken": #if(${context.arguments.after}) "${context.arguments.after}" #else null #end
        }
      ResponseMappingTemplate: |
        $utils.toJson($context.result.items)
  getAllMessageFromQueryResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: "Query"
      FieldName: "getAllMessageFrom"
      DataSourceName: !GetAtt MessageDynamoDBTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "operation" : "Query",
          "query" : {
              "expression": "conversationId = :id and sender = :sender",
              "expressionValues" : {
                  ":id" : {
                      "S" : "${context.arguments.conversationId}"
                  },
                  ":sender" : {
                      "S" : "${context.arguments.sender}"
                  }
              }
          },
          "index" : "sender",
          "limit": #if(${context.arguments.first}) ${context.arguments.first} #else 20 #end,
          "nextToken": #if(${context.arguments.after}) "${context.arguments.after}" #else null #end
        }
      ResponseMappingTemplate: |
        $utils.toJson($context.result.items)




  conversationUserConversationsResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: "UserConversations"
      FieldName: "conversation"
      DataSourceName: !GetAtt ConversationDynamoDBTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "operation" : "GetItem",
          "key" : {
              "id" : { "S" : "${context.source.conversationId}" }
          }
        }
      ResponseMappingTemplate: |
        $utils.toJson($context.result)


  associatedUserConversationsResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: "UserConversations"
      FieldName: "associated"
      DataSourceName: !GetAtt UserConversationsDynamoDBTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "operation" : "Query",
          "query" : {
              "expression": "conversationId = :conversationId",
              "expressionValues" : {
                  ":conversationId" : {
                      "S" : "${context.source.conversationId}"
                  }
              }
          },
          "index": "conversationId-index"
        }
      ResponseMappingTemplate: |
        $util.toJson($context.result.items)

  UpdateUserResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Mutation
      FieldName: updateUser
      DataSourceName: !GetAtt UserDynamoDBTableDataSource.Name
      RequestMappingTemplate: |
        {
            "version" : "2017-02-28",
            "operation" : "UpdateItem",
            "key" : {
                "username" : $util.dynamodb.toDynamoDBJson($context.arguments.username)
            },
            "update" : {
                "expression" : "SET wallets = :wallets",
                ## "expressionNames": {
                ##     "#url" : "url"
                ## },
                "expressionValues": {
                    ":wallets" : $util.dynamodb.toDynamoDBJson($context.arguments.wallets)
                }
            }
        }
      ResponseMappingTemplate: |
        ## Pass back the result from DynamoDB. **
        $util.toJson($ctx.result)