
AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito Stack
Parameters:
  ProjectName:
    Type: String
    Default: klubby
    Description: Unique Auth Name for Cognito Resources
  Stage:
    Type: String
    Default: dev
    Description: Stage of build
  NewUserFunction:
    Type: AWS::SSM::Parameter::Value<String>
    Default: add-new-user-funtion-dev
    Description: user table name
Resources:
  # Creates a role that allows Cognito to send SNS messages
  SNSRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: 
              Service: 
                - "cognito-idp.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "CognitoSNSPolicy"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: "sns:*"
                Resource: "*"
  # Creates a user pool in cognito for your app to auth against
  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Sub ${ProjectName}-user-pool-${Stage}
      AutoVerifiedAttributes:
        - email
      #   - phone_number
      # MfaConfiguration: "ON"
      # SmsConfiguration:
      #   ExternalId: !Sub ${ProjectName}-external
      #   SnsCallerArn: !GetAtt SNSRole.Arn
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
      EmailConfiguration:
        ConfigurationSet: !Ref ConfigSet
        EmailSendingAccount: DEVELOPER
        From: "no-reply@klubby.me"
        #TODO this was manually created
        SourceArn: !Sub "arn:aws:ses:us-east-1:${AWS::AccountId}:identity/klubby.me"
      LambdaConfig:
        PostConfirmation: !Ref NewUserFunction
      #   PostConfirmation: arn:aws:lambda:us-east-1:590503010210:function:add-new-user-function-dev-AddNewUserFunction-8wfT2fkun97F
      UsernameConfiguration:
        CaseSensitive: False
  UserPoolDomain: 
    Type: AWS::Cognito::UserPoolDomain 
    Properties:
      UserPoolId: !Ref UserPool 
      Domain: !Sub klubby-${Stage}
  UserPoolTokenClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
    #TODO understand these
      AllowedOAuthFlows:
        # - code
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - email
        - openid
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - https://klubby.me
      LogoutURLs:
        - https://klubby.me
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
      - USER_PASSWORD_AUTH
      SupportedIdentityProviders:
        - COGNITO
  # UserPoolUser:
  #    Type: AWS::Cognito::UserPoolUser
  #    Properties:
  #      DesiredDeliveryMediums:
  #        - EMAIL
  #      Username: bjudson@trek10.com
  #      UserPoolId: !Ref UserPool

  
  # # Creates a federeated Identity pool
  # IdentityPool:
  #   Type: "AWS::Cognito::IdentityPool"
  #   Properties:
  #     IdentityPoolName: !Sub ${ProjectName}-identity-pool-${Stage}
  #     AllowUnauthenticatedIdentities: true
  #     CognitoIdentityProviders:
  #       - ClientId: !Ref UserPoolTokenClient
  #         ProviderName: !GetAtt UserPool.ProviderName




  # # Create a role for unauthorized acces to AWS resources. Very limited access. Only allows users in the previously created Identity Pool
  # CognitoUnAuthorizedRole:
  #   Type: "AWS::IAM::Role"
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: "Allow"
  #           Principal:
  #             Federated: "cognito-identity.amazonaws.com"
  #           Action:
  #             - "sts:AssumeRoleWithWebIdentity"
  #           Condition:
  #             StringEquals:
  #               "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
  #             "ForAnyValue:StringLike":
  #               "cognito-identity.amazonaws.com:amr": unauthenticated
  #     Policies:
  #       - PolicyName: "CognitoUnauthorizedPolicy"
  #         PolicyDocument:
  #           Version: "2012-10-17"
  #           Statement:
  #             - Effect: "Allow"
  #               Action:
  #                 - "mobileanalytics:PutEvents"
  #                 - "cognito-sync:*"
  #               Resource: "*"

  # # Create a role for authorized acces to AWS resources. Control what your user can access. This example only allows Lambda invokation
  # # Only allows users in the previously created Identity Pool
  # CognitoAuthorizedRole:
  #   Type: "AWS::IAM::Role"
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: "Allow"
  #           Principal:
  #             Federated: "cognito-identity.amazonaws.com"
  #           Action:
  #             - "sts:AssumeRoleWithWebIdentity"
  #           Condition:
  #             StringEquals:
  #               "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
  #             "ForAnyValue:StringLike":
  #               "cognito-identity.amazonaws.com:amr": authenticated
  #     Policies:
  #       - PolicyName: "CognitoAuthorizedPolicy"
  #         PolicyDocument:
  #           Version: "2012-10-17"
  #           Statement:
  #             - Effect: "Allow"
  #               Action:
  #                 - "mobileanalytics:PutEvents"
  #                 - "cognito-sync:*"
  #                 - "cognito-identity:*"
  #               Resource: "*"
  #             - Effect: "Allow"
  #               Action:
  #                 - "lambda:InvokeFunction"
  #               Resource: "*"
  
  # # Assigns the roles to the Identity Pool
  # IdentityPoolRoleMapping:
  #   Type: "AWS::Cognito::IdentityPoolRoleAttachment"
  #   Properties:
  #     IdentityPoolId: !Ref IdentityPool
  #     Roles:
  #       authenticated: !GetAtt CognitoAuthorizedRole.Arn
  #       unauthenticated: !GetAtt CognitoUnAuthorizedRole.Arn




  ConfigSet:
    Type: 'AWS::SES::ConfigurationSet'
    Properties:
      Name: !Sub ses-configset-${Stage}

  InvokeAddNewUserFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NewUserFunction
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt UserPool.Arn

### SSM PARAMS ###
  UserPoolId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub userpool-id-${Stage}
      Type: String
      Value: !Ref UserPool
      Description: SSM Parameter for user pool id
      Tags:
        Environment: !Ref Stage