AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Default: klubby
    Description: Project name
    Type: String
  Stage:
    Default: dev
    Description: The deployment stage for this stack. Used to name a variety of different resources.
    Type: String
Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: !Sub 'user-table-${Stage}'
      AttributeDefinitions:
      - AttributeName: username
        AttributeType: S
      KeySchema:
      - AttributeName: username
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 10

  KlubTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: !Sub 'user-table-${Stage}'
      AttributeDefinitions:
      - AttributeName: klubname
        AttributeType: S
      KeySchema:
      - AttributeName: klubname
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 10

  UserKlubBridgeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: !Sub 'user-table-${Stage}'
      AttributeDefinitions:
      - AttributeName: klubname
        AttributeType: S
      - AttributeName: username
        AttributeType: S
      KeySchema:
      - AttributeName: klubname
        KeyType: HASH
      - AttributeName: username
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 10
      GlobalSecondaryIndexes:
        - IndexName: "username-index"
          KeySchema:
            - AttributeName: "username"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  ConversationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 10

  MessageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: conversationId
        AttributeType: S
      KeySchema:
      - AttributeName: conversationId
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 10

  UserConversationBridgeTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "conversationId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
        - AttributeName: "conversationId"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: "conversationId-index"
          KeySchema:
            - AttributeName: "conversationId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  KlubConversationBridgeTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "klubname"
          AttributeType: "S"
        - AttributeName: "conversationId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "klubname"
          KeyType: "HASH"
        - AttributeName: "conversationId"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: "conversationId-index"
          KeySchema:
            - AttributeName: "conversationId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5


### for landing page ###
  EmailDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: !Sub 'user-table-${Stage}'
      AttributeDefinitions:
      - AttributeName: email
        AttributeType: S
      KeySchema:
      - AttributeName: email
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 10


### SSM Params ###
  UserTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'user-table-name-${Stage}'
      Type: String
      Value: !Ref UserTable
      Description: SSM Parameter for user table name
      Tags:
        Environment: !Ref Stage

  ConversationTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'conversation-table-name-${Stage}'
      Type: String
      Value: !Ref ConversationTable
      Description: SSM Parameter for conversation table name
      Tags:
        Environment: !Ref Stage


  MessageTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'message-table-name-${Stage}'
      Type: String
      Value: !Ref MessageTable
      Description: SSM Parameter for message table name
      Tags:
        Environment: !Ref Stage

  UserConversationBridgeTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'userconversationbridge-table-name-${Stage}'
      Type: String
      Value: !Ref UserConversationBridgeTable
      Description: SSM Parameter for UserConversationBrdige table name
      Tags:
        Environment: !Ref Stage