AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Default: klubby
    Description: Project name
    Type: String
  Stage:
    Default: dev
    Description: The deployment stage for this stack. Used to name a variety of different resources.
    Type: String

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: !Sub 'user-table-${Stage}'
      AttributeDefinitions:
      - AttributeName: username
        AttributeType: S
      KeySchema:
      - AttributeName: username
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 3

  KlubTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: !Sub 'user-table-${Stage}'
      AttributeDefinitions:
      - AttributeName: klubname
        AttributeType: S
      KeySchema:
      - AttributeName: klubname
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 3

  UserKlubBridgeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: !Sub 'user-table-${Stage}'
      AttributeDefinitions:
      - AttributeName: klubname
        AttributeType: S
      - AttributeName: username
        AttributeType: S
      KeySchema:
      - AttributeName: klubname
        KeyType: HASH
      - AttributeName: username
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 3
      GlobalSecondaryIndexes:
        - IndexName: "username-index"
          KeySchema:
            - AttributeName: "username"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 3

  ConversationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 3

  MessageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: conversationId
        AttributeType: S
      KeySchema:
      - AttributeName: conversationId
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 3

  UserConversationBridgeTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "conversationId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
        - AttributeName: "conversationId"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 3
      GlobalSecondaryIndexes:
        - IndexName: "conversationId-index"
          KeySchema:
            - AttributeName: "conversationId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 3

  ContractTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: !Sub 'user-table-${Stage}'
      AttributeDefinitions:
      - AttributeName: address
        AttributeType: S
      KeySchema:
      - AttributeName: address
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 3

  AnnouncementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: !Sub 'user-table-${Stage}'
      AttributeDefinitions:
      - AttributeName: klubname
        AttributeType: S
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: klubname
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 3


### for landing page ###

  EmailDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: !Sub 'user-table-${Stage}'
      AttributeDefinitions:
      - AttributeName: email
        AttributeType: S
      KeySchema:
      - AttributeName: email
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 3

### SSM Params ###
  UserTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'user-table-name-${Stage}'
      Type: String
      Value: !Ref UserTable
      Description: SSM Parameter for user table name
      Tags:
        Environment: !Ref Stage

  ConversationTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'conversation-table-name-${Stage}'
      Type: String
      Value: !Ref ConversationTable
      Description: SSM Parameter for conversation table name
      Tags:
        Environment: !Ref Stage

  MessageTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'message-table-name-${Stage}'
      Type: String
      Value: !Ref MessageTable
      Description: SSM Parameter for message table name
      Tags:
        Environment: !Ref Stage

  UserConversationBridgeTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'userconversationbridge-table-name-${Stage}'
      Type: String
      Value: !Ref UserConversationBridgeTable
      Description: SSM Parameter for UserConversationBrdige table name
      Tags:
        Environment: !Ref Stage


  UserKlubBridgeTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'userklubbridge-table-name-${Stage}'
      Type: String
      Value: !Ref UserKlubBridgeTable
      Description: SSM Parameter for UserKlubBrdige table name
      Tags:
        Environment: !Ref Stage        



  KlubTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'klub-table-name-${Stage}'
      Type: String
      Value: !Ref KlubTable
      Description: SSM Parameter for klub table name
      Tags:
        Environment: !Ref Stage

  ContractTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'contract-table-name-${Stage}'
      Type: String
      Value: !Ref ContractTable
      Description: SSM Parameter for contract table name
      Tags:
        Environment: !Ref Stage

  AnnouncementTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'announcement-table-name-${Stage}'
      Type: String
      Value: !Ref AnnouncementTable
      Description: SSM Parameter for announcement table name
      Tags:
        Environment: !Ref Stage