AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Default: klubby
    Description: Project name
    Type: String
  Stage:
    Default: dev
    Description: The deployment stage for this stack. Used to name a variety of different resources.
    Type: String
Resources:
  UserDynamoTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: !Sub 'user-table-${Stage}'
      AttributeDefinitions:
      - AttributeName: username
        AttributeType: S
      KeySchema:
      - AttributeName: username
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 10
  MessageDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: message_id
        AttributeType: S
      KeySchema:
      - AttributeName: message_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 10

  ConversationDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: conversation_id
        AttributeType: S
      KeySchema:
      - AttributeName: conversation_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 10

  EmailDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: !Sub 'user-table-${Stage}'
      AttributeDefinitions:
      - AttributeName: email
        AttributeType: S
      KeySchema:
      - AttributeName: email
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 10

### SSM Params ###
  UserTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'user-table-name-${Stage}'
      Type: String
      Value: !Ref UserDynamoTable
      Description: SSM Parameter for user table name
      Tags:
        Environment: !Ref Stage

  ConversationTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub 'conversation-table-name-${Stage}'
      Type: String
      Value: !Ref ConversationDynamoTable
      Description: SSM Parameter for user table name
      Tags:
        Environment: !Ref Stage