
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Default: klubby
    Description: Project name
    Type: String
  Stage:
    Default: dev
    Description: The deployment stage for this stack. Used to name a variety of different resources.
    Type: String
  SrcBucket:
    Description: Bucket with the src code for lib
    Type: String
  # SrcBucket:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Default: layer-src-bucket-name-dev
  #   Description: Bucket with the src code for lib
MyLayer:
  Type: AWS::Lambda::LayerVersion
  Properties:
    CompatibleRuntimes:
      # - python3.6
      - python3.9
    Content:
      S3Bucket: !Ref SrcBucket
      S3Key: lib.zip
    Description: lib layer
    LayerName: lib-layer
    LicenseInfo: MIT