AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  join-klub

  Join a given klub for a given user

Globals:
  Function:
    Timeout: 3

Resources:
  JoinKlubFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: join_klub/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

### SSM PARAMS ###
  JoinKlubFunctionArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub join-klub-function-arn-${Stage}
      Type: String
      Value: !GetAtt JoinKlubFunction.Arn
      Description: SSM Parameter for user ARN of user status management function
      Tags:
        Environment: !Ref Stage